language_translate = {
    'Graphics editor': ['Graphics editor', 'Графический редактор'],
    'open file': ['open file', 'открыть файл'],
    'save': ['save', 'сохранить'],
    'language': ['choose russian language', 'choose english'],
    'blur': ['blur', 'размытие'],
    'step back': ['step back', 'шаг назад'],
    'blur radius': ['blur radius', 'радиус размытия'],
    'vertical mirror': ['vertical mirror', 'вертикальное отражение'],
    'horizontal mirror': ['horizontal mirror', 'горизонтальное отражение'],
    'transparency': ['transparency', 'прозрачность'],
    'transparency percentage': ['transparency percentage', 'процент прозрачности'],
    'filter': ['filter', 'фильтр'],
    'step forward': ['step forward', 'шаг вперёд'],
    'trim along the x-axis': ['trim along the x-axis', 'обрезать по оси x'],
    'pixels left': ['pixels left', 'пикселей слева'],
    'pixels right': ['pixels right', 'пикселей справа'],
    'trim along the y-axis': ['trim along the y-axis', 'обрезать по оси y'],
    'pixels on top': ['pixels on top', 'пикселей сверху'],
    'pixels bottom': ['pixels bottom', 'пикселей снизу'],
    'turn right': ['turn right', 'повернуть вправо'],
    'turn left': ['turn left', 'повернуть влево'],
    'information': ['information', 'информация'],
    'size': ['size', 'размер'],
    'turn on draw': ['turn on draw', 'вкл рисование'],
    'turn off draw': ['turn off draw', 'выкл рисование'],
    'color': ['color', 'цвет'],
    'delete layer': ['delete layer', 'удалить слой'],
    'add layer': ['add layer', 'добавить слой']
}
max_showing_image_size = [1000, 650]
